version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
    timezone: America/Toronto
  open-pull-requests-limit: 3
  ignore:
  - dependency-name: activerecord
    versions:
    - "> 5.2.3"
  - dependency-name: omniauth
    versions:
    - 2.0.1
  - dependency-name: pry
    versions:
    - 0.13.1
