language: ruby

rvm:
- "2.6.6"

env:
  - DEVELOPMENT=1

gemfile:
  - Gemfile

script:
  - bundle exec rake db:schema:load
  - bundle exec rake test

notifications:
  email:
    on_success: never
    on_failure: never
